DTS-STN/Scrum-Poker

- .github/README.md
Changing ReadME to start it off.
More will come as this project evolves.
> Changing ReadME.

- .github/workflows/comment-environment.yml
- .github/workflows/security.yml
- .teamcity/pom.xml
- .teamcity/settings.kts
- load-test.js
changed next-template to Scrum-Poker in the ks file for Team City
Created a new project in Team City in Dev as Dev_ScrumPoker
Not sure if I got all of the required files for Team City
Hopefully I got the right syntax for each of the changes.
> replaced template for scrum poker

- .github/pull_request_template.md
- .teamcity/settings.kts
Changed Scrum-Poker to scrum-poker in hopefully the correct places.
-
-
> Dum 5 ks fix

- pages/room/[id].js
Added shell of room page
try loading /room/[id]
id will display on page
> added room page

- components/Card.js
- components/Card.test.js
- pages/room/[id].js
Added basic functionality to select a card and display the value selected.
> Select a card functionality.

- pages/room/[id].js
- Added locale to room page
- Fixed langToggleLink
> DUMS-35 Translation not working on room

- __tests__/pages/home.test.js
- components/HomeCardContainer.js
- components/HomeCardContainer.test.js
- components/TextInput.js
- components/TextInput.test.js
- locales/en.js
- locales/fr.js
- pages/home.js
Our design has color contrast issues so the colors are not the same as in Figma.
Added home container cards with no functionality.
The styling is not exactly the same. If we prefer to follow exactly the design please let me know and I will try to match it 100%.
The buttons are not exactly the same as I am waiting to see if we are using DECD or not.
Try different browser width.
> Dums 47 home container cards

- __tests__/pages/home.test.js
- graphql/client.js
- graphql/queries/example.graphql
- jest.config.js
- next.config.js
- package-lock.json
- package.json
- pages/_app.js
- pages/home.js
- pages/room/[id].js
- Installed and initialized Apollo Client
- Left in Proof of Concept GraphQL query that fetches books as an example
- Queries can be created in graphql/queries and then called inside functions using Hooks: (useQuery, useMutation, useSubscription, etc.)
- Tests will need to be created for used queries with mock data.
> DUMS-39 Add Apollo Client

- components/Card.js
- locales/en.js
- locales/fr.js
- pages/room/[id].js
- Added buttons for Hide, Show, Clear based on Figma designs
- Added cursor hover to card component :)
- Recreated PR
- Supertask buttons and Primary buttons can be moved into a component?
> DUMS-55 Create placeholder buttons - Hide, Show, Clear

- components/Player.js
- components/UserList.js
had the wrong prop type, should have been an object but was a string.
-
-
> Dums 16 propfix

- .teamcity/settings.kts
- locales/en.js
check out the kotlin file changes to see what got fixed.
> fixing missing variable

- components/RoomInfo.js
- components/RoomInfo.test.js
- locales/en.js
- locales/fr.js
- pages/room/[id].js
Added room info box as a component with 
- added room info box along with the copy to clipboard functionality
- requires changes for translation of the labels
- download and run
> Dums 24 copy roomv2

- .github/workflows/comment-environment.yml
- .teamcity/settings.kts
> updating the dynamic branches url and creating the cleanup script for TC

- .teamcity/settings.kts
> adding imports

- components/Card.js
- components/Card.test.js
- components/Player.js
- components/Player.test.js
- components/UserList.js
- pages/room/[id].js
Added tests for Player component. 
added tests for Player component and fixed act warning on card component. 
updated skip link for room page
> Dums 57 tests

- components/RoomInfo.js
- pages/room/[id].js
changed the props type to be a number to avoid a warning message 
- Proptype changed to a number instead of string 
- N/A
> Dums 24 copy roomv3

- __tests__/pages/home.test.js
- graphql/queries/addRoom.graphql
- graphql/queries/addUser.graphql
- pages/home.js
Front-end refinement to create user first, and then create room.
> Skeleton for creating a room and a user.

- components/ErrorLabel.js
- components/ErrorLabel.test.js
- locales/en.js
- locales/fr.js
- pages/home.js
This PR adds validation for creating a new room. Whenever the user clicks the `Create Room` button, there is a first a check to see if the user name is either empty or contains special characters before a room is created. If either of those flags are true, an error label is shown above the text input.
1. Pull in branch
2. Type `npm run dev`
3. In order to prevent from flooding the server with new rooms, you can comment out lines 56-62 in `home.js`
4. Click create room without entering anything, an error message should show up
5. Enter in `name!` into the text input and click create room, an error message should show up
6. Enter in a valid name and click create room (if you followed step 3 there should be no error but nothing else will happen. without the lines commented you'll be sent to …
> Added client side validation for room creation

- components/UserList.js
- graphql/queries/getUsers.graphql
- pages/home.js
- pages/room/[id].js
The name is being displayed on the room page after creating the room.
- Small refinement code. Please let me know what should be changed! :)
> Fetch user object

- graphql/queries/getRoomByID.graphql
- graphql/queries/getUsers.graphql
- pages/room/[id].js
Changed query to get all information related to the current room.
- How do we want to handle different page states?
- Test will come after we know what the behavior should be depending on the room state.
Don't be shy to throw in your input, please. We are a team! :D
> Roomid check when joining or creating a room.

- package-lock.json
- package.json
##NEXT 12.1.1 update
Updated next as next/Image was causing issues in 12.1.0
> NEXT 12.1.1 update

- pages/home.js
- pages/room/[id].js
Getting rid of the ownerID cookie. Using the room.host object instead.
> Removing ownerid cookie.

- graphql/mutations/updateUser.graphql
- pages/home.js
- pages/room/[id].js
> reworked create room button

- graphql/queries/getRoomByID.graphql
- pages/room/[id].js
- Added mutation to update server-side data whenever user changes their card selection
> DUMS-79 Mutations whenever a card is clicked.

- graphql/queries/updateRoomByID.graphql
- pages/home.js
- Join room button now adds room code to user object
- Refactored joinRoomHandler based on createRoomHandler
> Updated Join Room Handler

- .github/workflows/test-and-lint.yml
- components/Player.js
- pages/home.js
updated the regex to include - and a longer or double name.
centered the letter for the name in the list. 
check the names to make sure that it works to allow a - and a name with up to 4 parts. (if that is what is wanted?)
> longer names and fix for letter

- .github/README.md
- .gitignore
- package-lock.json
- package.json
- pages/home.js
- pages/room/[id].js
playing around with using js-cookie package
> initial stuff

- .teamcity/settings.kts
> Adding Production TC Job

- Dockerfile
speaks for itself, if it runs and deploys it should be good... check out the docker file
> adding users/groups for docker

- components/Container.js
- components/DateModified.js
- pages/home.js
-Commented out the description text (it can be added back if there is something we want to say there) 
-Changed from style to className as style doesn't build the same as className locally and moved around some of the styling so now it looks good on mobile and other sizes. (Things can still be moved around if needed but for now it looks good)
-Adjusted the margin on the date modified. 
-Removed the dropshadow on the text as it made it look fuzzy. 
-
-
> Dums 108 rmtext

- components/ChatRoom.js
- components/Player.js
- components/RoomInfo.js
- components/TextInput.js
- components/UserList.js
- locales/en.js
- locales/fr.js
- pages/home.js
- pages/room/[id].js
Added an asterisk to the required fields, not sure if we also want to add text for it but right now it's a pretty universal symbol for required. 
removed the unused code for the description. 
-
-
> Dums 110 required

- components/Card.js
- components/Player.js
- pages/room/[id].js
made the cards in the player list smaller
updated the top border to match once a card is selected
-
-
> made cards smaller

- components/Footer.js
- components/RoomInfo.js
- components/TextInput.js
- locales/en.js
- locales/fr.js
This PR modifies the Leave Room button design and also has a couple padding fixes around the copy id button
1. Pull in branch
2. Type `npm run dev`
3. Create a room
4. Look at RoomInfo component
> Leave button redesign and fixes

- locales/en.js
- locales/fr.js
- pages/home.js
adds alphanumeric/required validation for room code on home page.  Also added translation, but the french part will need to be updated.
> fixing client side validation for room code

- components/ErrorLabel.js
- components/TextInput.js
- locales/en.js
- locales/fr.js
- pages/home.js
- pages/room/[id].js
updated the regex for the join room user
fixed up the spacing of the error messages.
-
-
> adjusted regex and placement of alert

- pages/room/[id].js
select the infinity card and look at the message near the top.
> updating the code to use infinity symbol instead of 100 when selected

- locales/en.js
- pages/home.js
Styled the page error message so that it looks the same as the other items on the page with left and right margins.
Added an 'a' to the error message.
> page error fits in container

- graphql/client.js
- graphql/mutations/updateRoom.graphql
- graphql/queries/getRoom.graphql
- pages/home.js
- Fixed the join room mutation to take timer object and set of cards
> Join room mutation fix

- components/Container.js
- components/CreateRoom.js
- components/JoinRoom.js
- pages/home.js
adjusted the layout slightly for the JoinRoom and CreateRoom components. 
-
-
> Layout fix

- components/CreateRoom.js
- pages/room/[id].js
- utils/cards.js
Moved logic for displaying card values and style into cards object
Added ability to get card by value (sudo id)
To test, try creating a room and click all card buttons
> Bug fix: Displaying 0 on card select

- pages/home.js
oops I cleaned up a bit too much
This fix places the page error back at the top above the other items. 
-
-
> fixes the location of the page error

- locales/en.js
- locales/fr.js
- pages/home.js
- pages/room/[id].js
Small PR that changes the redirect link when a user is booted from or leaves a room so a message is shown on the homepage notifying them that they were removed.
1. Pull in branch
2. Type `npm run dev`
3. Create a room
4. Join the room on another browser
5. Boot the joiner from the room
6. You should see an error message on the home page that says `You have been removed from the room`
> Added error label for when user is removed from room

- components/UserList.js
- pages/room/[id].js
> if currPlay is missing in globalUserId, set cookied value to it

- .github/README.md
Add clearer instructions on how to get the web app and server running together and connected
Check to see if the added explanation in the README is clear
> README Update

- components/UserList.js
Sort the UserList by vote
- The list is only sorted while it's shown and not hidden
Check to see if the UserList is sorted when the cards are shown
> Sort userList by vote

- components/Player.js
Fix the issue with tailwind not changing the user background color
Run the code locally and join room 85723
Check to see if the users Tommy and Ben have different colors apart from grey
> Change color

- components/ChatRoom.js
- locales/en.js
- locales/fr.js
- pages/room/[id].js
> Translation Tweaks

- .teamcity/README.md
- Dockerfile
- next.config.js
Just a small change to trigger TC build
-
-
> small change

- components/CreateRoom.js
- components/JoinRoom.js
Add dev level console logging for object on Create/Join room components
Check to see if there's a console log when we create or join a room
> Dev level logs
